package win32

import "syscall"

var (
	Kernel32                     = syscall.NewLazyDLL("kernel32.dll")
	ProcOpenProcess              = Kernel32.NewProc("OpenProcess")
	ProcReadProcessMemory        = Kernel32.NewProc("ReadProcessMemory")
	ProcEnumProcessModules       = Kernel32.NewProc("K32EnumProcessModules")
	ProcGetModuleBaseNameW       = Kernel32.NewProc("K32GetModuleBaseNameW")
	ProcGetModuleHandleW         = Kernel32.NewProc("GetModuleHandleW")
	ProcCreateToolhelp32Snapshot = Kernel32.NewProc("CreateToolhelp32Snapshot")
	ProcProcess32FirstW          = Kernel32.NewProc("Process32FirstW")
	ProcProcess32NextW           = Kernel32.NewProc("Process32NextW")
	ProcCloseHandle              = Kernel32.NewProc("CloseHandle")
	ProcWaitForSingleObject      = Kernel32.NewProc("WaitForSingleObject")
	ProcGetConsoleWindow         = Kernel32.NewProc("GetConsoleWindow")
	ProcGetConsoleProcessList    = Kernel32.NewProc("GetConsoleProcessList")
	ProcCreateMutexW             = Kernel32.NewProc("CreateMutexW")
	ProcGetUserDefaultLocaleName = Kernel32.NewProc("GetUserDefaultLocaleName")

	User32                         = syscall.NewLazyDLL("user32.dll")
	ProcRegisterClassExW           = User32.NewProc("RegisterClassExW")
	ProcMessageBoxW                = User32.NewProc("MessageBoxW")
	ProcCreateWindowExW            = User32.NewProc("CreateWindowExW")
	ProcShowWindow                 = User32.NewProc("ShowWindow")
	ProcSetWindowPos               = User32.NewProc("SetWindowPos")
	ProcUpdateWindow               = User32.NewProc("UpdateWindow")
	ProcSetLayeredWindowAttributes = User32.NewProc("SetLayeredWindowAttributes")
	ProcGetMessageW                = User32.NewProc("GetMessageW")
	ProcTranslateMessage           = User32.NewProc("TranslateMessage")
	ProcDispatchMessageW           = User32.NewProc("DispatchMessageW")
	ProcBeginPaint                 = User32.NewProc("BeginPaint")
	ProcEndPaint                   = User32.NewProc("EndPaint")
	ProcPostMessageW               = User32.NewProc("PostMessageW")
	ProcSendMessageW               = User32.NewProc("SendMessageW")
	ProcPostQuitMessage            = User32.NewProc("PostQuitMessage")
	ProcDestroyWindow              = User32.NewProc("DestroyWindow")
	ProcDefWindowProcW             = User32.NewProc("DefWindowProcW")
	ProcGetCursorPos               = User32.NewProc("GetCursorPos")
	ProcGetDC                      = User32.NewProc("GetDC")
	ProcEnumWindows                = User32.NewProc("EnumWindows")
	ProcGetWindowThreadProcessId   = User32.NewProc("GetWindowThreadProcessId")
	ProcIsWindowVisible            = User32.NewProc("IsWindowVisible")
	ProcGetClientRect              = User32.NewProc("GetClientRect")
	ProcClientToScreen             = User32.NewProc("ClientToScreen")
	ProcInvalidateRect             = User32.NewProc("InvalidateRect")
	ProcReleaseDC                  = User32.NewProc("ReleaseDC")
	ProcFillRect                   = User32.NewProc("FillRect")
	ProcDrawTextW                  = User32.NewProc("DrawTextW")
	ProcGetSystemMetrics           = User32.NewProc("GetSystemMetrics")
	ProcLoadIconW                  = User32.NewProc("LoadIconW")
	ProcLoadImageW                 = User32.NewProc("LoadImageW")
	ProcCreatePopupMenu            = User32.NewProc("CreatePopupMenu")
	ProcAppendMenuW                = User32.NewProc("AppendMenuW")
	ProcTrackPopupMenu             = User32.NewProc("TrackPopupMenu")
	ProcDestroyMenu                = User32.NewProc("DestroyMenu")
	ProcSetForegroundWindow        = User32.NewProc("SetForegroundWindow")
	ProcFindWindowW                = User32.NewProc("FindWindowW")
	ProcSetWindowsHookExW          = User32.NewProc("SetWindowsHookExW")
	ProcCallNextHookEx             = User32.NewProc("CallNextHookEx")
	ProcUnhookWindowsHookEx        = User32.NewProc("UnhookWindowsHookEx")
	ProcRegisterHotKey             = User32.NewProc("RegisterHotKey")
	ProcUnregisterHotKey           = User32.NewProc("UnregisterHotKey")

	Shell32             = syscall.NewLazyDLL("shell32.dll")
	ProcShellNotifyIcon = Shell32.NewProc("Shell_NotifyIconW")
	ProcShellExecuteW   = Shell32.NewProc("ShellExecuteW")

	Gdi32                = syscall.NewLazyDLL("gdi32.dll")
	ProcCreateSolidBrush = Gdi32.NewProc("CreateSolidBrush")
	ProcCreatePen        = Gdi32.NewProc("CreatePen")
	ProcCreateFontW      = Gdi32.NewProc("CreateFontW")
	ProcSelectObject     = Gdi32.NewProc("SelectObject")
	ProcDeleteObject     = Gdi32.NewProc("DeleteObject")
	ProcSetBkMode        = Gdi32.NewProc("SetBkMode")
	ProcSetTextColor     = Gdi32.NewProc("SetTextColor")
	ProcMoveToEx         = Gdi32.NewProc("MoveToEx")
	ProcLineTo           = Gdi32.NewProc("LineTo")
	ProcGetPixel         = Gdi32.NewProc("GetPixel")
)
